name: flutter_application_utswdk
description: "A new Flutter project."
publish_to: "none" # Remove this line if you want to publish to pub.dev
version: 0.1.0+1 # You can use the format `major.minor.patch+build`

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # Add other dependencies here as needed
  # For example, if you are using HTTP requests:
  # http: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
